theme: jekyll-theme-primer
title: Project overview
description: Overall report of the project
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
